apiVersion: v1
kind: Service
metadata:
  name: bangez-service
  labels:
    app: bangez-service
spec:
  type: LoadBalancer
  ports:
    - name: gateway
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: eureka
      protocol: TCP
      port: 8761
      targetPort: 8761
    - name: tx
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: user
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: land
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: analysis
      protocol: TCP
      port: 8084
      targetPort: 8084
    - name: chat
      protocol: TCP
      port: 8085
      targetPort: 8085


  selector:
    app: bangez